require("dotenv").config();
const fs = require("fs");
const path = require("path");
const { Pool } = require("pg");

// =====================================================
// JALANKAN MIGRATION 001_extend_schema.sql KE DATABASE
// Pakai: node scripts/runMigration.js
// Aman dijalankan berkali-kali (idempotent).
// =====================================================

const pool = new Pool({
    host: process.env.PGHOST,
    port: Number(process.env.PGPORT) || 5432,
    database: process.env.PGDATABASE,
    user: process.env.PGUSER,
    password: process.env.PGPASSWORD,
    ssl: process.env.PGSSL === "true" ? { rejectUnauthorized: false } : false,
});

async function jalankan() {
    const client = await pool.connect();
    try {
        console.log("Terhubung ke database:", process.env.PGDATABASE);

        // 1) Tambah kolom baru ke monitoring_sensor (aman diulang, pakai IF NOT EXISTS)
        await client.query(`
            ALTER TABLE public.monitoring_sensor
                ADD COLUMN IF NOT EXISTS suhu_air numeric(5,2),
                ADD COLUMN IF NOT EXISTS tds numeric(6,2),
                ADD COLUMN IF NOT EXISTS ppm numeric(6,2),
                ADD COLUMN IF NOT EXISTS water_level_percent numeric(5,2),
                ADD COLUMN IF NOT EXISTS water_level_height numeric(5,2);
        `);
        console.log("✅ Kolom monitoring_sensor sudah lengkap");

        // 2) Buat tabel actuator_log kalau belum ada
        const cekTabel = await client.query(`
            SELECT to_regclass('public.actuator_log') AS ada
        `);
        const tabelSudahAda = cekTabel.rows[0].ada !== null;

        if (!tabelSudahAda) {
            await client.query(`
                CREATE TABLE public.actuator_log (
                    id integer NOT NULL,
                    actuator_name varchar(50) NOT NULL,
                    status varchar(10) NOT NULL,
                    started_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
                    ended_at timestamp,
                    duration_seconds integer,
                    CONSTRAINT actuator_log_status_check CHECK (status IN ('ON', 'OFF')),
                    CONSTRAINT actuator_log_name_check CHECK (
                        actuator_name IN ('pompa_air', 'lampu_led', 'exhaust_fan')
                    )
                );
            `);

            await client.query(`
                ALTER TABLE public.actuator_log ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
                    SEQUENCE NAME public.actuator_log_id_seq
                    START WITH 1
                    INCREMENT BY 1
                    NO MINVALUE
                    NO MAXVALUE
                    CACHE 1
                );
            `);

            await client.query(`
                ALTER TABLE ONLY public.actuator_log
                    ADD CONSTRAINT actuator_log_pkey PRIMARY KEY (id);
            `);

            console.log("✅ Tabel actuator_log berhasil dibuat");
        } else {
            console.log("ℹ️  Tabel actuator_log sudah ada, dilewati");
        }

        // 3) Index (aman diulang, pakai IF NOT EXISTS)
        await client.query(`
            CREATE INDEX IF NOT EXISTS idx_actuator_log_started_at ON public.actuator_log (started_at);
            CREATE INDEX IF NOT EXISTS idx_actuator_log_name ON public.actuator_log (actuator_name);
            CREATE INDEX IF NOT EXISTS idx_monitoring_sensor_created_at ON public.monitoring_sensor (created_at);
        `);
        console.log("✅ Index sudah lengkap");

        console.log("\n🎉 Migration selesai. Silakan restart backend (npm run dev).");
        process.exit(0);
    } catch (err) {
        console.error("❌ Migration gagal:", err.message);
        process.exit(1);
    } finally {
        client.release();
    }
}

jalankan();