-- Migration: melengkapi skema agar sesuai kebutuhan frontend I-WILL Greenhouse
-- Jalankan ini SETELAH db_greenersfix.sql (skema aslinya) di-restore.

-- 1) Tabel monitoring_sensor: tambah kolom yang belum ada tapi dipakai frontend
--    (suhu air, TDS, PPM/turbidity, ketinggian air tandon)
ALTER TABLE public.monitoring_sensor
    ADD COLUMN IF NOT EXISTS suhu_air numeric(5,2),
    ADD COLUMN IF NOT EXISTS tds numeric(6,2),
    ADD COLUMN IF NOT EXISTS ppm numeric(6,2),
    ADD COLUMN IF NOT EXISTS water_level_percent numeric(5,2),
    ADD COLUMN IF NOT EXISTS water_level_height numeric(5,2);

-- 2) Tabel log aktuator (Pompa Air, Lampu LED, Exhaust Fan)
--    Dipakai untuk grafik "Pemakaian Aktuator" di halaman Statistik
CREATE TABLE IF NOT EXISTS public.actuator_log (
    id integer NOT NULL,
    actuator_name varchar(50) NOT NULL,      -- 'pompa_air' | 'lampu_led' | 'exhaust_fan'
    status varchar(10) NOT NULL,             -- 'ON' | 'OFF'
    started_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    ended_at timestamp,
    duration_seconds integer,
    CONSTRAINT actuator_log_status_check CHECK (status IN ('ON', 'OFF')),
    CONSTRAINT actuator_log_name_check CHECK (
        actuator_name IN ('pompa_air', 'lampu_led', 'exhaust_fan')
    )
);

ALTER TABLE public.actuator_log OWNER TO postgres;

ALTER TABLE public.actuator_log ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.actuator_log_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

ALTER TABLE ONLY public.actuator_log
    ADD CONSTRAINT actuator_log_pkey PRIMARY KEY (id);

CREATE INDEX IF NOT EXISTS idx_actuator_log_started_at ON public.actuator_log (started_at);
CREATE INDEX IF NOT EXISTS idx_actuator_log_name ON public.actuator_log (actuator_name);
CREATE INDEX IF NOT EXISTS idx_monitoring_sensor_created_at ON public.monitoring_sensor (created_at);
